---

- name: Ensure dendencies are present
  pacman:
    name: "{{ item }}"
  loop:
    - make
    - gmp
    - bison
    - flex


- name: Create temporary installation directory
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
  loop:
    - "{{ src_dir }}"
    - "{{ tmp_dir }}"

- name: Fetch openswan sources
  get_url:
    url: "{{ openswan_url }}"
    dest: "{{ tmp_dir }}/openswan.tar.gz"

- name: Extract the archive's content
  unarchive:
    src: "{{ tmp_dir }}/openswan.tar.gz"
    dest: "{{ src_dir }}"
    extra_opts: [--strip-components=1]

- name: Compile openswan
  make:
    chdir: "{{ src_dir }}"
    target: programs

- name: Install openswan
  make:
    chdir: "{{ src_dir }}"
    target: install
  become: true
